// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1QggZNvhu6Rb-749DPBv9gs--xxrhkY',
    appId: '1:1083006566648:web:39999c8602f749d7a17b0d',
    messagingSenderId: '1083006566648',
    projectId: 'eventvista-90ce3',
    authDomain: 'eventvista-90ce3.firebaseapp.com',
    storageBucket: 'eventvista-90ce3.appspot.com',
    measurementId: 'G-XH92EM828Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC01i3V2BSys76LaDgNQ7vy9amMsLG83v8',
    appId: '1:1083006566648:android:592c2b4ce2c472b2a17b0d',
    messagingSenderId: '1083006566648',
    projectId: 'eventvista-90ce3',
    storageBucket: 'eventvista-90ce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7GkewpsnsFmYgK2ddGD_6fJIa_Z7daj4',
    appId: '1:1083006566648:ios:d43981a3e4f05fdca17b0d',
    messagingSenderId: '1083006566648',
    projectId: 'eventvista-90ce3',
    storageBucket: 'eventvista-90ce3.appspot.com',
    iosBundleId: 'com.example.eventvista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7GkewpsnsFmYgK2ddGD_6fJIa_Z7daj4',
    appId: '1:1083006566648:ios:b7420378fc4109c1a17b0d',
    messagingSenderId: '1083006566648',
    projectId: 'eventvista-90ce3',
    storageBucket: 'eventvista-90ce3.appspot.com',
    iosBundleId: 'com.example.eventvista.RunnerTests',
  );
}
